### ISSUE TITLE
Error while creating a new game 

### ISSUE THREAD

**Issue by junaidookay** [TobeTek/blitz-of-the-hidden-soldiers-fe#3]
Hi,

I tried to play against my friend last night using the link you provided (https://blitz-of-the-hidden-soldiers.web.app/me) but I couldn't, as whenever I pasted his address, while creating a new game, I got this error: 

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
    at Et.buildInstance (index-b2b105ca.js:4400:48766)
    at async Et.getInstance (index-b2b105ca.js:4400:48594)
    at async b (index-b2b105ca.js:4426:20886)

Also, I was not able to view the Active Games Page or the Tournaments Page. I am new to this stuff and I am learning along the way. It would be great help if you can guide me in the right direction and fix the issue for us.

Thank you.

**Comment by TobeTek** [comment]
Hi @junaidookay,

Thanks for your interest in BoTHS!

BoTHS is still very much in beta, and the publicly available version isn't ready for play yet.

Please join the [waitlist](https://forms.gle/vtegaZQEZGZcLpV39) to stay up to date on new releases and updates.

You can also check out a sneak peek into a bit of what has been built so far: https://twitter.com/onambatech/status/1741108461801263413

Thank you!
